### ISSUE TITLE
Tests fail to compile on GHC 8.2.1

### ISSUE THREAD

**Issue by nh2** [fpco/store#111]
I get this:

```
[4 of 6] Compiling Data.StoreSpec   ( test/Data/StoreSpec.hs, dist/build/store-test/store-test-tmp/Data/StoreSpec.dyn_o )

test/Data/StoreSpec.hs:272:11: error:
    • No instance for (Serial IO CBlkSize)
        arising from a use of ‘smallcheck-1.1.1:Test.SmallCheck.Property.changeDepth’
    • In the expression:
        (smallcheck-1.1.1:Test.SmallCheck.Property.changeDepth (\ _ -> 2))
      In the second argument of ‘($)’, namely
        ‘((smallcheck-1.1.1:Test.SmallCheck.Property.changeDepth
             (\ _ -> 2))
            $ (\ x_aSDO -> (checkRoundtrip False) (x_aSDO :: CBlkSize)))’
      In the second argument of ‘($)’, namely
        ‘(Test.Hspec.SmallCheck.property
            $ ((smallcheck-1.1.1:Test.SmallCheck.Property.changeDepth
                  (\ _ -> 2))
                 $ (\ x_aSDO -> (checkRoundtrip False) (x_aSDO :: CBlkSize))))’
    |
272 |         $(do insts <- getAllInstanceTypes1 ''Store
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

**Comment by nh2** [comment]
Probably this: https://downloads.haskell.org/~ghc/8.2.1-rc1/docs/html/libraries/base-4.10.0.0/System-Posix-Types.html#t:CBlkSize

`newtype CBlkSize`

> Since: 4.10.0.0

**Comment by mgsloan** [comment]
Thanks for the report!  Fixed in https://github.com/fpco/store/commit/d6dfa5a159306607138840de192d4aa867ad4ef3

Seems like behavior of what is included in the instances for class reification has changed.  Not sure how it's changed, though.  The gist here shows both ghc 8 and ghc 8.2 having iffy behavior here - https://gist.github.com/mgsloan/a7c416b961015949d3b5674ce053bbf6 - but with that minimal repro it is consistent.
