### ISSUE TITLE
Dependency issues with `mono-traversable` and `vector`

### ISSUE THREAD

**Issue by mniip** [fpco/store#183]
`store-0.7.19` and `store-0.7.20` declare `build-depends: mono-traversable >= 0.7.0`, but they fail to build when `mono-traversable <=1.0.20.0` and `vector >=1.13.2.0` are in use:
```
src/Data/Store/Internal.hs:393:12: error: [GHC-39999]
    • Could not deduce ‘IsSequence (SCV.Vector a)’
        arising from a use of ‘pokeSequence’
      from the context: Store a
        bound by the instance declaration
        at src/Data/Store/Internal.hs:391:10-40
      There are instances for similar types:
        instance Storable a => IsSequence (SV.Vector a)
          -- Defined in ‘Data.Sequences’
        instance UV.Unbox a => IsSequence (UV.Vector a)
          -- Defined in ‘Data.Sequences’
        instance IsSequence (V.Vector a) -- Defined in ‘Data.Sequences’
    • In the expression: pokeSequence
      In an equation for ‘poke’: poke = pokeSequence
      In the instance declaration for ‘Store (SCV.Vector a)’
    |
393 |     poke = pokeSequence
    |            ^^^^^^^^^^^^
```
This instance `IsSequence (Data.Vector.Strict.Vector a)` is only introduced in `mono-traversable-1.0.21.0` and is [documented as such](https://hackage.haskell.org/package/mono-traversable-1.0.21.0/docs/src/Data.Sequences.html#line-1122).

Note that the code in question in `store` and the instance in `mono-traversable` are both guarded behind an `#if MIN_VERSION_vector(0,13,2)`, meaning that the constraint `build-depends: mono-traversable >=1.0.21` is only necessary when `vector >=0.13.2` is selected.

This issue is introduced in #180

**Comment by mniip** [comment]
Actually there's more:
- In #148 compatibility with `vector >=0.12.1.2` was fixed. This landed in `store-0.7.2`, but `store >=0.1.0.0 && <=0.7.1` still need hackage revisions to restrict `build-depends: vector <0.12.1.2`.
- In #174 compatibility with `vector >=0.13` was fixed. This landed in `store-0.7.16`, and some older versions were even revised to `build-depends: vector <0.13`, but `store >=0.7.2 && <=0.7.11` still need revisions.

**Comment by mniip** [comment]
Also a couple revision issues that aren't relevant to `vector` or `mono-traversable`:

- store `>=0.5.0 && <0.7.14` don't support `text >=2` (fixed in fa393119b4c377b993aafc9f6873d2e54c0fe3e5)
- store `0.7.0` doesn't support GHC 7.10 (fixed in 009f0a537bebcd4ccbd61538c82cd0d38d4c45ef)
- store `0.6.0` doesn't support GHC 7.10 (fixed in 7178e12d6dff79f8971038ca8f32c8f1afe98325)
- store `>=0.7.19` (and git head) don't support GHC <8.0 (DerivingStrategies added in 8.2) (unfixed)
