### PR TITLE
Fix build with GHC-8.8

### LINKED ISSUE #144: Support for GHC-8.8
`store-core` currently fails to build:

```
src/Data/Store/Core.hs:115:5: error: 
    ‘fail’ is not a (visible) method of class ‘Monad’ 
    | 
115 |     fail = pokeException . T.pack 
    |     ^^^^ 
 
src/Data/Store/Core.hs:116:16: error: 
    The INLINE pragma for ‘fail’ lacks an accompanying binding 
      (The INLINE pragma must be given where ‘fail’ is declared) 
    | 
116 |     {-# INLINE fail #-} 
    |                ^^^^ 
 
src/Data/Store/Core.hs:231:5: error: 
    ‘fail’ is not a (visible) method of class ‘Monad’ 
    | 
231 |     fail = peekException . T.pack 
    |     ^^^^ 
 
src/Data/Store/Core.hs:232:16: error: 
    The INLINE pragma for ‘fail’ lacks an accompanying binding 
      (The INLINE pragma must be given where ‘fail’ is declared) 
    | 
232 |     {-# INLINE fail #-} 
    |                ^^^^ 
```

head.hackage has a patch: https://gitlab.haskell.org/ghc/head.hackage/blob/b0af1b02c5c94a5a5b104fc9ed66eed470945622/patches/store-core-0.4.4.patch

… and also one for `store`: https://gitlab.haskell.org/ghc/head.hackage/blob/b0af1b02c5c94a5a5b104fc9ed66eed470945622/patches/store-0.5.1.2.patch

### PR DESCRIPTION
**Pull request by sjakobi**
This applies the following head.hackage patches:

* https://gitlab.haskell.org/ghc/head.hackage/blob/b0af1b02c5c94a5a5b104fc9ed66eed470945622/patches/store-core-0.4.4.patch
* https://gitlab.haskell.org/ghc/head.hackage/blob/b0af1b02c5c94a5a5b104fc9ed66eed470945622/patches/store-0.5.1.2.patch

Fixes #144.

### CODE REVIEW

**Comment by sjakobi** [comment]
https://github.com/fpco/th-utilities/pull/8 will have to be released before this can actually be compiled with GHC-8.8.

**Comment by mgsloan** [comment]
LGTM, thanks!  I've released store-streaming-0.2.0.0  store-core-0.4.4.1 store-0.6.0

**Comment by sjakobi** [comment]
Thanks for the quick release @mgsloan! :)

And thanks to @RyanGlScott for all the patches! :+1:

**Comment by Bodigrim** [comment]
As a hackage trustee I made appropriate revisions to old releases of `store` to prohibit unbuildable configurations.
