### ISSUE TITLE
Version 0.4.3.1 fails to build with GHC 8.2.1 and cabal-install 2.0.0.0

### ISSUE THREAD

**Issue by centromere** [fpco/store#112]
```
$ cabal install --allow-newer stack-1.5.0
Resolving dependencies...
Configuring store-0.4.3.1...
Building store-0.4.3.1...
Failed to install store-0.4.3.1
Build log ( /home/alex/.cabal/logs/ghc-8.2.1/store-0.4.3.1-EkbDeYEvc8E5BQvh9QLvPO.log ):
cabal: Entering directory '/tmp/cabal-tmp-32116/store-0.4.3.1'
Configuring store-0.4.3.1...
Preprocessing library for store-0.4.3.1..
Building library for store-0.4.3.1..
[ 1 of 11] Compiling Data.Store.Impl  ( src/Data/Store/Impl.hs, dist/build/Data/Store/Impl.o )
[ 2 of 11] Compiling Data.Store.Streaming.Internal ( src/Data/Store/Streaming/Internal.hs, dist/build/Data/Store/Streaming/Internal.o )
[ 3 of 11] Compiling Data.Store.TH.Internal ( src/Data/Store/TH/Internal.hs, dist/build/Data/Store/TH/Internal.o )
[ 4 of 11] Compiling Data.Store.TH    ( src/Data/Store/TH.hs, dist/build/Data/Store/TH.o )
[ 5 of 11] Compiling Data.Store.Internal ( src/Data/Store/Internal.hs, dist/build/Data/Store/Internal.o )

src/Data/Store/Internal.hs:110:1: error:
    Could not find module ‘Data.Typeable.Internal’
    it is a hidden module in the package ‘base-4.10.0.0’
    Use -v to see a list of the files searched for.
    |
110 | import           Data.Typeable.Internal (Typeable)
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Leaving directory '/tmp/cabal-tmp-32116/store-0.4.3.1'
cabal: Error: some packages failed to install:
stack-1.5.0-AeEyMtn08gzB8Y5bVGRiVl depends on stack-1.5.0 which failed to
install.
store-0.4.3.1-EkbDeYEvc8E5BQvh9QLvPO failed during the building phase. The
exception was:
ExitFailure 1
```

**Comment by centromere** [comment]
Apologies. The latest version of the master branch builds correctly.
