### PR TITLE
Fix #179. Support for vector-0.13.2.0

### LINKED ISSUE #179: `store` no longer compiles with new version `vector-0.13.2.0`.
E.g. and many similar error messages appear:
```
/home/curators/work/unpack-dir/unpacked/store-0.7.18-6e9fb2c1c59a9f2fb62abd0016841417b57b9a3e045088d48d65cc740cb1eeb9/src/Data/Store/Internal.hs:824:2: error: [GHC-39999]
           • No instance for ‘Store a’ arising from a use of ‘peek’
             Possible fix:
               add (Store a) to the context of the instance declaration
           • In a stmt of a 'do' block: c0f0 <- peek
             In the expression:
               do c0f0 <- peek
                  return (Data.Vector.Unboxed.Base.V_DoNotUnboxLazy c0f0)
             In an equation for ‘peek’:
                 peek
                   = do c0f0 <- peek
                        return (Data.Vector.Unboxed.Base.V_DoNotUnboxLazy c0f0)
           |
       824 | $(deriveManyStoreUnboxVector)
           |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I will disable this package on stackage for now.
(fyi @snoyberg).

### PR DESCRIPTION
**Pull request by jcmartin**
This pull request addresses #179.

### CODE REVIEW

**Comment by jcmartin** [comment]
As of now, snoyberg/mono-traversable#244 has been resolved, and this merge request now needs review.

@mgsloan This is ready for your review :)

**Comment by mgsloan** [comment]
Awesome, thank you!!

**Comment by jcmartin** [comment]
It seems the CI is failing due to a misconfiguration:

```
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```

I did not touch anything to do with the CI config.

**Comment by mgsloan** [comment]
Uploaded `store-0.7.19` to hackage

**Comment by jcmartin** [comment]
@mgsloan Great! Thank you for your quick work!
